spring:
  application:
    name: mini-ecom
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:mini_ecom}
    username: ${POSTGRES_USER:mini_ecom}
    password: ${POSTGRES_PASSWORD:mini_ecom}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8080
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    filter: true
    try-it-out-enabled: true
    doc-expansion: none
    default-models-expand-depth: -1
